class Config:
    WINDOW_SIZE = (1920, 1010)
    TITLE = "Pyfactorio"
    FPS = 60

    #MAP CONFIG
    MAP_SIZE = 200
    
    #MAP RENDER CONFIG
    TILES_SIZE = 20
    
    #INVENTORY CONFIG
    MAX_STACK_SIZE = 64
    
    #INVENTORY RENDER CONFIG
    INVENTORY_CELL_SIZE = 60